---
- name: Build Docker images for fullstack app
  hosts: localhost
  tasks:
    - name: Build backend image
      community.docker.docker_image:
        name: sarah1mo/backend-demo
        build:
          path: ./demo
          nocache: true   # ğŸ‘ˆ ÙŠÙƒØ³Ø± Ø§Ù„ÙƒØ§Ø´ Ù„Ù„Ø¨Ø§Ùƒ Ø§Ù†Ø¯
        source: build

    - name: Build frontend image
      community.docker.docker_image:
        name: sarah1mo/frontend-app
        build:
          path: ./frontend
          nocache: true   # ğŸ‘ˆ ÙŠÙƒØ³Ø± Ø§Ù„ÙƒØ§Ø´ Ù„Ù„ÙØ±ÙˆÙ†Øª Ø§Ù†Ø¯
        source: build
